osx_image: xcode8
language: objective-c
xcode_workspace: CollectionViewPractice.xcworkspace
xcode_schemes: CollectionViewPractice

profile: Podfile

before_install:
 - echo $CODE && pod install #--project-directory=Example
 
script:
 - xcodebuild -workspace CollectionViewPractice.xcworkspace -scheme CollectionViewPractice -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO


 
