osx_image: xcode8
language: objective-c
xcode_workspace: CollectionViewPractice.xcworkspace
xcode_schemes: CollectionViewPractice

profile: Podfile

before_script:
 - pod install
 
script:
 - xcodebuild -workspace CollectionViewPractice.xcworkspace -scheme CollectionViewPractice -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO

after_script:
- curl -F "file=/Users/travis/Library/Developer/Xcode/DerivedData/CollectionViewPractice-cwnguqtfrmlhnaamtbfpxcnqytrk/Build/Products/Debug-iphonesimulator/CollectionViewPractice.app" -F "uKey=$uKey" -F "_api_key=$apiKey" https://www.pgyer.com/apiv1/app/upload

